// // This file is automatically generated. Do not modify it manually.
// // This file was generated by Firebase Studio.
// //
// // These configuration values are public.
// //
// export const firebaseConfig = {
//   apiKey: 'FIXME',
//   authDomain: 'FIXME',
//   projectId: 'FIXME',
//   storageBucket: 'FIXME',
//   messagingSenderId: 'FIXME',
//   appId: 'FIXME',
// };
